---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omnitruck
resources:
  - kubernetes/deployment.yaml
  - kubernetes/gloo.yaml
  - kubernetes/hpa.yaml
  - kubernetes/cron.yaml
  - kubernetes/namespace.yaml
  - kubernetes/serviceaccount.yaml
  - kubernetes/service.yaml 